Feat/show all food
istodaymeatballsday/API pull request #1
Opened 2019-04-18 13:06 UTC by mattssonj

Will add 2 fields to the response. A response will look like eg:
{ msg: "Nope.", code: 1, meat: "some meat dish", veg: "some veg dish" }

2019-04-18 13:14 UTC, mattssonj commented
Just realized this doesn't handle when express is closed.

2019-04-18 13:22 UTC, mattssonj commented
When expressen is closed veg will now also show closed.

2019-04-19 13:11 UTC, anthager requested changes

2019-04-19 13:11 UTC, anthager commented on utils/importantFunctions.ts
> +getTodaysMealCode().then(resp => console.log(resp))
This will trigger the function when this file is imported. I.e. The function will be triggered twice on a lambda call
```suggestion

```

2019-04-19 13:11 UTC, anthager commented on utils/importantFunctions.ts
> +  let today = await getFood(getCurrentDate());
This variable is never reassigned,
```suggestion
  const today = await getFood(getCurrentDate());
```

2019-04-23 08:46 UTC, mattssonj commented on utils/importantFunctions.ts
> +getTodaysMealCode().then(resp => console.log(resp))
forgot testing print in pull. Removed!

2019-04-23 08:46 UTC, mattssonj commented on utils/importantFunctions.ts
> +  let today = await getFood(getCurrentDate());
fixed!

2019-04-23 08:47 UTC, mattssonj commented
All changes fixed. Please Review again

2019-04-23 08:56 UTC, anthager commented
Nice job, looks good

2019-04-23 08:56 UTC, merged